<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ntkaut\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ntkaut/appProdProjectContainer.php') {
    touch(__DIR__.'/Container2ntkaut.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container2ntkaut\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container2ntkaut\appProdProjectContainer([
    'container.build_hash' => '2ntkaut',
    'container.build_id' => '1c0f1ff1',
    'container.build_time' => 1636389002,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ntkaut');
