<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnwb5vt\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnwb5vt/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCnwb5vt.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCnwb5vt\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCnwb5vt\appProdProjectContainer([
    'container.build_hash' => 'Cnwb5vt',
    'container.build_id' => '3a5af2ca',
    'container.build_time' => 1637777473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnwb5vt');
